import type { Metadata } from "next";
import { primaryFont } from '@/lib/fonts/fonts';
import "./globals.css";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Master Hub",
  description: "Generated by create next app",
  icons: {
    icon: '/vanquish.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <link rel="image_src" href="/vanquish.svg" />
      </head>
      <body
        data-theme="dark"
        className={`${primaryFont.variable} bg-background text-cta-text font-primary antialiased`}
      >
        <Providers>

          {children}
        </Providers>
      </body>
    </html>
  );
}
