import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Master Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <link rel="image_src" href="/logo.png" />
      </head>
      <body
        data-theme="dark"
        className={`${geistSans.variable} ${geistMono.variable} bg-background text-cta-text font-primary antialiased`}
      >
        <Providers>

          {children}
        </Providers>
      </body>
    </html>
  );
}
